// actions
export const SUBMIT_MASS_MAIL_FORM = 'SUBMIT_MASS_MAIL_FORM'
export const SET_FORM_INPUT_FIELD = 'SET_FORM_INPUT_FIELD'
export const SET_FORM_INPUT_ERROR = 'SET_FORM_INPUT_ERROR'
export const SET_FORM_SERVER_ERROR = 'SET_FORM_SERVER_ERROR'
export const RESET_FORM_INPUT_FIELDS = 'RESET_FORM_INPUT_FIELDS'
export const RESET_FORM_INPUT_ERROR = 'RESET_FORM_INPUT_ERROR'
export const RESET_FORM_SERVER_ERROR = 'RESET_FORM_SERVER_ERROR'

// loaders
export const IS_MASS_MAIL_FORM_SUBMITTING = 'isMassMailFormSubmitting'

// state for mass mail
export const MASS_MAIL_FORM = 'massMail'
export const MASS_MAIL_SUBJECT_FIELD = 'massMailSubject'
export const MASS_MAIL_BODY_FIELD = 'massMailBody'

// misc
export const FORM_INPUT_TYPE_TEXT = 'FORM_INPUT_TYPE_TEXT'
export const FORM_INPUT_TYPE_TEXTAREA = 'FORM_INPUT_TYPE_TEXTAREA'
export const FORM_INPUT_TYPE_PASSWORD = 'FORM_INPUT_TYPE_PASSWORD'
export const FORM_INPUT_TYPE_SELECT = 'FORM_INPUT_TYPE_SELECT'
export const FORM_INPUT_TYPE_RADIO = 'FORM_INPUT_TYPE_RADIO'
